### ISSUE TITLE
Support for SonarQube 7.9.x LTS

### ISSUE THREAD

**Issue by alixwar** [kwoding/sonar-webdriver-plugin#2]
This plugin is not available in the Marketplace for the (at the time of writing) new LTS version of SonarQube.

Will you make a release that is officially supported in the new version?

**Comment by kwoding** [comment]
The release currently in the marketplace is actually already compatible with the current LTS version. See here a screenshot of SonarQube 7.9.1 running with this plugin available in the marketplace.

![sonarqube791_sonar_webdriver](https://user-images.githubusercontent.com/22679606/66634780-15be4880-ec0e-11e9-9913-8473c254776e.png)

However, I did just upgraded the internal sonar versions to be in sync with 7.9.1 and already contacted SonarSource on this with a new release. Expected to be available soon.

**Comment by kwoding** [comment]
New release now also available in 7.9.1 marketplace. As mentioned before, previous version was already available. This new release is just a technical release (internal library versions updated).
