### ISSUE TITLE
Is this plugin available for checking Cucumber-Selenium projects in Maven?

### ISSUE THREAD

**Issue by azcama** [kwoding/sonar-webdriver-plugin#5]
Hello!
I'm developing a Maven project with Cucumber and Selenium. Therefore, my main source is in the test folder due to the requirements for the execution of the runner that starts all the scenarios and my src folder is empty. I installed the plugin in my localhost sonar with the marketplace.

I've checked that your recommendations is to execute both separated with these conditions:

`mvn sonar:sonar -Dsonar.projectKey=<my project>-tests -Dsonar.host.url=http://localhost:9000 -Dsonar.login=<a valid token> -Dsonar.sources=src/test -Dsonar.test.inclusions=src/test/java`

However, I put the same conditions in my pom.xml and the response is:
`[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar (default-cli) on project cucumber-selenium: File src/test/java/testSteps/ShopOrderSteps.java can't be indexed twice. Please check that inclusion/exclusion patterns produce disjoint sets for main and test files -> [Help 1]
`

So, for solving this problem I had to put my pom.xml with these values:
`<sonar.sources>src/test/java</sonar.sources>
 <sonar.tests></sonar.tests>`

Then, it works. But I would like to ask you, even if my source is in the test folder (without any part in src) and it is based in Cucumber and Selenium, does this plugin work? Because, I'm not able to see any advice related to WebDrivers. I'm comparing the results before installing your plugin and after installing your plugin, and there are not any new data in the reports.

Thanks in advance!
Azahara.

**Comment by kwoding** [comment]
Test sources can be scanned separately, just like you have solved it yourself. What is the specific case that it does not work? Do you mean that you have sources, but NOT under a `src` folder? It should still work as long as you set the `sonar.sources` accordingly

**Comment by azcama** [comment]
I finally got it. I've just check the list of rules with the tag Webdriver and there they are! They are very helpful for improving the SeleniumWebdriver tests! Thanks a lot for your contribution!
